[project]
name = "hullstockprediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.0.0",
    "jupyter>=1.1.1",
    "kaggle>=1.7.4.5",
    "pandas>=2.3.3",
]
